apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          - name: mysql-initdb
            mountPath: /docker-entrypoint-initdb.d
          - name: mysql-persistent-storage
            mountPath: "/var/lib/mysql"
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  initdb.sql: |
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'db_project' AND table_name = 'users') THEN
    CREATE TABLE `users` (`userId` int NOT NULL AUTO_INCREMENT,`username` varchar(45) DEFAULT NULL,`password` varchar(45) DEFAULT NULL,PRIMARY KEY (`userId`) ) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
    INSERT INTO `db_project`.`users`(`userId`, `username`,`password`) VALUES('user1','password1'),(`user2`,`password`);

    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_schema = 'db_project' AND table_name = 'tasks') THEN
        CREATE TABLE `tasks` (
        `idtasks` int NOT NULL AUTO_INCREMENT,
        `name` varchar(45) DEFAULT NULL,
        `status` tinyint DEFAULT NULL,
        `userId` int DEFAULT NULL,
        PRIMARY KEY (`idtasks`),
        KEY `userId_idx` (`userId`),
        CONSTRAINT `userId` FOREIGN KEY (`userId`) REFERENCES `users` (`userId`)
            ) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

    END IF;