apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentification-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentification-server
  template:
    metadata:
      labels:
        app: authentification-server
    spec:
      containers:
      - name: authentification-server
        image: bllopp/cloud-service:latest
        ports:
        - containerPort: 4000
        env:
        - name: MYSQL_HOST
          value: mysql
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "db_project"
---
apiVersion: v1
kind: Service
metadata:
  name: your-app-service
spec:
  selector:
    app: your-app
  ports:
  - protocol: TCP
    port: 4000
    targetPort: 4000
  type: NodePort
